name: CI

on:
  push:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Call netlify build hook
      env:
        HOOK_URL: ${{ secrets.HOOK_URL }}
      run: |
        curl -X POST -d {} $HOOK_URL
        date
